version: "3"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=tasklist
      - MONGO_INITDB_ROOT_USERNAME=testuser
      - MONGO_INITDB_ROOT_PASSWORD=testpassword
    ports:
      - "27017:27017"